spring:
  datasource:
    url: jdbc:mariadb://db.gdgoc-team3.site:3306/gdgoc
    username: gdgoc
    password: ${GDGOC_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true      # 쿼리 로깅 활성화
    properties:
      hibernate:
        format_sql: true